### ISSUE TITLE
snippets in mails triggered from admin are ignored

### ISSUE THREAD

**Issue by gnnrp** [FriendsOfShopware/FroshPlatformTemplateMail#11]
Hi,

thanks for this great plugin! Helps a lot for my workflow but I found an issue:

All mails triggered from admin (e.g. status mails, user password forgotten) do not use snippets. All mails send via frontend like order purchase are working fine with snippets. The Bug already existed in sw 6.2.3 and is also present in sw 6.3.0.2.

**How to reproduce?**
1. Create snippet in custom theme:
`{"theme": {
    "email": {
        "user_recovery_request": {
            "title": "Reset Password"
            }
        }
    }
}`

2. Write snippet in email/global/user.recovery.request/html.twig:
`{{'theme.email.user_recovery_request.title'|trans}}`

3. Request new User Passwort via /admin login page and check mail content

**Result**
- Mail content is:
_theme.email.user_recovery_request.title_

**Expected result**
- Mail content is:
_Reset Password_

Let me know if I can support somehow!

**Comment by TimWuyts** [comment]
I'm experiencing a similar issue when sending emails (triggered by an external plugin) originating from a CLI command.
The underlying code is using the default MailService from Shopware core, causing the following unexpected behavior:
- Email template is not fetched from my theme, the content as provided in the database is still provided. However the "froshMailTemplate" extension is being set correctly by the MailTemplateSubscriber. Not sure where the actual 'contentHtml' is swapped within the FroshPlatformTemplateMail codebase?
- Custom translations originating from my theme are not being applied, while core string translations are being applied correctly.

**Comment by TimWuyts** [comment]
Already managed to work around my first issue, using a subscriber on the "MailBeforeValidateEvent" & replacing the specific templates using the "MailFinderService". 

The translation issue remains the same, although the "fixTranslator" function from the "MailFinderService" gets successfully called.
