### ISSUE TITLE
Not Triggered with Order Mail Distributor 

### ISSUE THREAD

**Issue by develth** [FriendsOfShopware/FroshPlatformTemplateMail#13]
Hello,

when Using the Plugin [Order Mail Distributor](https://store.shopware.com/swag407923290380f/order-mail-distributor.html) the TemplateMail is not triggered and "DataBase" Mail is used.

Is it something this Plugin could control?

Thanks!

**Comment by shyim** [comment]
Since Order Mail Distributor is dead. Use Event Actions
