### ISSUE TITLE
Wrong template used when folder named by locale code

### ISSUE THREAD

**Issue by st-heymer** [FriendsOfShopware/FroshPlatformTemplateMail#14]
When using a storefront in German (with English as default shop language), and with having all mails in folders identified by their locale codes (so mails in German are in `custom/plugins/MyTheme/src/Resources/views/email/de-DE`, English in `custom/plugins/MyTheme/src/Resources/views/email/en-GB`, the mail sent out will be in the fallback language (i.e. English).

A test showed that the order of languages has to be reversed in `FroshPlatformTemplateMail::findTemplateByTechnicalName` on line 70:
```
foreach (array_reverse($languages) as $language) {
      array_unshift($searchFolder, $language->getLocale()->getCode());
}
```

**Comment by shyim** [comment]
Thanks!

Feel free next time to create a PR
