### ISSUE TITLE
Email templating

### ISSUE THREAD

**Issue by raincity19** [FriendsOfShopware/FroshPlatformTemplateMail#17]
Hello, probably my question is simple, but anyway:
Where can i find all names of the existing in the backend emails to be templated? Your example works with order_transaction.state.paid only. I cannot find the correct paths for other emails.  In your plugin there is no view-folder, where the default templates could be placed. 
And one more question:
Is it possible to template also the footer and header? Or they should the part of the order_transaction.state.paid/html.twig? 

Thank you in advance.

**Comment by shyim** [comment]
The names are the acutual template names from the database.  Should be in the mail_template_type table
