### ISSUE TITLE
Snippets are not being replaced when template from cache

### ISSUE THREAD

**Issue by edvvogel** [FriendsOfShopware/FroshPlatformTemplateMail#19]
We are using snippets within twig-templates to render the mails.
However, we experienced in production environment that the first mail of each type is always sent correctly while the second has non-replaced snippets within.

When we change the CachedMailFinderService:findTemplateByTechnicalName line
$cacheItem->expiresAfter(3600) to $cacheItem->expiresAfter(0) everything works fine.

**Comment by zolthan** [comment]
I have a similar behavior. The Cache Key seems to general. If we use the SalesChannelId and LanguageId additionally, the cache is working again.

```PHP
        $cacheKey = md5($type . $technicalName . $businessEvent->getName() . json_encode($businessEvent->getConfig()) . $businessEvent->getEvent()->getSalesChannelContext()->getSalesChannel()->getId() . $businessEvent->getEvent()->getSalesChannelContext()->getSalesChannel()->getLanguageId());
```

I'm working on a merge request.

**Comment by shyim** [comment]
The fix applied on master. Can you test the master to confirm that the bug is fixed?

**Comment by zolthan** [comment]
For me unfortunately not, as we have Shopware 6.3.2.1. maybe the thread starter could confirm the fix.

**Comment by shyim** [comment]
The master is compatible to all 6.3 and 6.4

**Comment by zolthan** [comment]
With the new patch I provided my bug seems fixed. The "Forgot Password" mail is now sent in different languages. Before fixing the issue it was always sent in the language that is cached.
