### ISSUE TITLE
"lorenzo/pinky ^1.0" error

### ISSUE THREAD

**Issue by XenousPrime** [FriendsOfShopware/FroshPlatformTemplateMail#23]
### Question

By installing of the plugin "Mail Templates aus dem Theme verwenden" I have the following error:
<b>Failed Dependency
Required plugin/package "lorenzo/pinky ^1.0" is missing or not installed and activated</b>

I installed the extension php-lorenzo-pinky and also was installing the composer file with composer require lorenzo/pinky
In Plesk the composer file lorenzo/pinky is shown.
We use Shopware 6.4.3.0

Can you give an advice?

**Comment by shyim** [comment]
Download https://github.com/FriendsOfShopware/FroshPluginUploader

Run ext:prepare in the plugin folder
