### ISSUE TITLE
Support for new "Flow Builder" functionality.

### ISSUE THREAD

**Issue by TimWuyts** [FriendsOfShopware/FroshPlatformTemplateMail#26]
### Please describe the feature you would like to see implemented.

Since the "Business Events" are becoming deprecated due to the upcoming "Flow Builder", I'm wondering if there will be any support for this on release day? 

I'm currently working on an e-commerce project, that is about to go live & the "Flow Builder" is a welcome addition to that. I have this new functionality successfully running now using the feature flag, but I've noticed that this plugin has no support yet. 

I'm willing to help to piece together a PR in order to achieve this functionality.
But I'm also struggling with my limited Symfony skills as a mainly front-end focussed developer.

**Comment by shyim** [comment]
Is added with https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/commit/c0798938ed9fe3d82ad72c766b3526385c5b2c5b
