### ISSUE TITLE
Mjml include tag does not work

### ISSUE THREAD

**Issue by memoworker** [FriendsOfShopware/FroshPlatformTemplateMail#27]
### Please describe the feature you would like to see implemented.

Hello Frosh Developers,

Currently the mjml include tag does not work due to the limitations of the code.

Is there a specific reason why the mjml gets parsed through an api endpoint and not by a php mjml parser bundle?
This also creates the problem that if the endpoint is down the shop will stop sending mails as it will not be able to parse them.

Would you be interested in a PR that changes the parsing behaviour to use a php bundle to fix both of those issues?

**Comment by memoworker** [comment]
We just made some more research and have seen, that no easy to use php library exists for parsing the template files.

Therefore we would suggest the following changes.

1. Resolve mjml include tags directly from the file content by inserting it into the data. Relative paths should be possible and start from the file currently loaded.
2. Caching of templates (Using the Symfony Cache Component). This would fix the strong reliance on the API and relieve it of some load.
3. If the API is not available return the plaintext template instead of throwing an error (and therefore not sending the mail).

If this is also agreed upon by you we will create a PR for those suggestions.

**Comment by shyim** [comment]
Maybe like this https://github.com/FriendsOfShopware/FroshTemplateMailMjml/blob/master/Components/WebMjmlCompiler.php#L100

**Comment by memoworker** [comment]
Thanks for the input @shyim we just created a pull request with the caching and resolving of include tags.
We had to adapt the regex as the one supplied in the Shopware 5 Plugin did not work.

**Comment by jakobpevec** [comment]
Hello!

I've noticed that relative paths do not resolve properly with mjml include. 

Folder structure:

sl-SI/includes/header.mjml
sl-SI/order_transaction.state.paid/html.mjml

Include path in html.mjml: ../includes/header.mjml

On send event the path resolves like this, triggering an error:
src/Resources/views/email/sl-SI/order_transaction.state.paid/../includes/header.mjml
