### ISSUE TITLE
Failed Dependency

### ISSUE THREAD

**Issue by rathhb** [FriendsOfShopware/FroshPlatformTemplateMail#30]
### Question

Hi there,
When trying to install the plugin I get the following error message:

"Failed Dependency
Required plugin/package "lorenzo/pinky ^1.0" is missing or not installed and activated"

System is SW 6.441, PHP is 7.427

Can you help me?

Thanks & Greetings

**Comment by shyim** [comment]
Please use release zip
https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/releases/download/0.4.3/FroshPlatformTemplateMail.zip

**Comment by vardumper** [comment]
Same behavior for me with the release from your zip.

**Comment by jakobpevec** [comment]
Same issue here, when installing that release

**Comment by tinect** [comment]
This issue has been resolved with the latest dependency update.
