### ISSUE TITLE
BusinessEvents are gone

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/FroshPlatformTemplateMail#32]
### Actual behaviour

`\Frosh\TemplateMail\Services\MailFinderService::findTemplateByTechnicalName` uses `BusinessEvent` but as far as I can tell, the BusinessEvents have been replaced with `MailAware`.

### Expected behaviour

Should use the correct event.

### Steps to Reproduce?

Use latest Shopware version

**Comment by shyim** [comment]
it works currently using https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/blob/master/src/Subscriber/FlowSubscriber.php
