### ISSUE TITLE
Correct state for a New order

### ISSUE THREAD

**Issue by jonas-sfx** [FriendsOfShopware/FroshPlatformTemplateMail#38]
### Question

I created src/Resources/views/email/global/order_transaction.state.open/subject.twig, plain.twig and html.twig 
in the Template Directory custom/plugins/MyCoolCustomThemeName .

But New OrderConfirmation Mails are not using this template-Files. They still use what

Did I read the Specs wrong?
Is order_transaction.state.open not an order-transaction-state?

**Comment by shyim** [comment]
should be ` order_transaction.state.open`. You can use the new command to dump all files
