### ISSUE TITLE
Version 2.0.1 ist not compatible with shopware version 6.5.3.2

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshPlatformTemplateMail#50]
### PHP Version

8.1.16

### Shopware Version

6.4.20

### Actual behaviour

Hey, I can’t install the newest version of froshformtemplatemail plugin 2.0.1 via “composer require store.shopware.com/froshplatformtemplatemail” because it’s not compatible with shopware version 6.4.20. It requires shopware at least version 6.5.0.
  Problem 1
    - [store.shopware.com/froshplatformtemplatemail[2.0.0](http://store.shopware.com/froshplatformtemplatemail[2.0.0), ..., 2.0.1] require shopware/core ~6.5.0 -> found shopware/core[dev-trunk, 6.5.0.0-dev, 6.5.0.0-rc1, 6.5.0.0-rc2, 6.5.x-dev (alias of dev-trunk)] but it does not match your minimum-stability.
    - Root composer.json requires [store.shopware.com/froshplatformtemplatemail](http://store.shopware.com/froshplatformtemplatemail) ^2.0 -> satisfiable by [store.shopware.com/froshplatformtemplatemail[2.0.0](http://store.shopware.com/froshplatformtemplatemail[2.0.0), 2.0.1].

### Expected behaviour

Please check the compatibility with shopware version 6.4.20

### Steps to Reproduce?

composer require store.shopware.com/froshplatformtemplatemail

**Comment by getnatalia** [comment]
You get in production code a lot of console errors in administration like this:
app.js?16793892208375437:2 An error was captured in current module: ReferenceError: salesChannel is not defined
app.js?16793892208375437:2 An error was captured in current module: ReferenceError: customerRecovery is not 
etc

If you switch to development mode this errors disappear.

**Comment by getnatalia** [comment]
![E-Mail-Templates___Shopware_Administration](https://user-images.githubusercontent.com/64019313/226588490-b7a47ef2-d3ed-4c70-b708-386454ccc645.png)

**Comment by getnatalia** [comment]
I'm currently using version 1.0.0

**Comment by getnatalia** [comment]
Yes, by plugin deactivating the errors disappear.

**Comment by getnatalia** [comment]
The same bug appears with shopware version 6.5.3.1 and plugin version 2.0.1.
I have 2 sales channels with different themes. Each theme has own mail templates e.g.
myproject/first-theme/src/Resources/views/email/global/order_confirmation_mail and myproject/second-theme/src/Resources/views/email/global/order_confirmation_mail.

**Comment by shyim** [comment]
I cannot reproduce the Composer or Administration issue.

What's the real problem here 🙈

**Comment by getnatalia** [comment]
Hey, i'm testing with shop in a **production** mode (in .env set to APP_ENV=prod ), with shopware version 6.5.3.2 and plugin version 2.0.1. I get the errors like "app.js?1689249532:2 An error was captured in current module: ReferenceError: salesChannel is not defined" and An error was captured in current module: ReferenceError: userRecovery is not defined, for every mail template variable in Settings -> Email templates
![Email_templates___Shopware_Administration](https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/assets/64019313/0b6f500e-8a40-4e6c-b993-9a0c5877f1e5).

The emails are sent correctly, but there are a lot of error messages displayed and also in log entries.
Is this information helpful for you?

**Comment by getnatalia** [comment]
![Use_mail_templates_from_theme___Shopware_Store](https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/assets/64019313/6070380b-c9a2-4a5f-a8f6-4be04253c495)

**Comment by shyim** [comment]
Does this error come maybe because of other extensions?

**Comment by getnatalia** [comment]
hm, I have deactivated all extensions. Only the plugin for mail templates and my theme are still active.

**Comment by getnatalia** [comment]
This preview only works in dev mode.
When switching to production mode, no preview is displayed. At mouse-over, more browser errors appear in the console.
![Eingefügtes_Bild_14_07_23__11_08](https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/assets/64019313/692c18d6-d088-45db-b685-25f64e86ed41)

**Comment by getnatalia** [comment]
Can you reproduce the issue? Do you need more info?
