### ISSUE TITLE
Allow to specify MJML server

### ISSUE THREAD

**Issue by nickygerritsen** [FriendsOfShopware/FroshPlatformTemplateMail#54]
### Please describe the feature you would like to see implemented.

Currently the MJML server is hardcoded, but it would be cool if we could specify our own, maybe as a config setting on the plugin.

If this is something people are interested in, I could cook up a PR.

**Comment by shyim** [comment]
Sure feel free to make a PR. I would rather make it configureable using Symfony Configuration like we do in FroshTools.

**Comment by nickygerritsen** [comment]
That's also fine for me, and probably easier anyway.
