### ISSUE TITLE
Snippets are not working after Shopware update to 6.5.5.1

### ISSUE THREAD

**Issue by riaspirjak** [FriendsOfShopware/FroshPlatformTemplateMail#56]
### PHP Version

8.2

### Shopware Version

6.5.5.1

### Actual behaviour

After updating Shopware (6.5.3 to 6.5.5) the snippets in my email templates are not translated anymore. Instead of adding the translations from my snippet files it just displays the snippet code.

**Example:** 

This is the snippet in my email template (MyTheme/src/Resources/views/email/global/order_confirmation_mail/html.twig): 
{{ 'email.order.confirmation.content.ordernumber'|trans }}

Displayed in the sent email like this:
email.order.confirmation.content.ordernumber

### Expected behaviour

All snippets should be translated based on the snippet files.

### Steps to Reproduce?

I installed the FroshPlatformTemplateMail plugin with Shopware 6.5.3 added some changes and snippets to the confirmation email template. Everything worked as expected, the email was overridden correctly, and also all translations were added as expected from my snippet JSON files. 

After updating Shopware to version 6.5.5.1 the emails were still correctly overridden but the snippets were not translated anymore.

Thanks a lot for your help!

**Comment by shyim** [comment]
Can you try 6.5.5.2?

**Comment by riaspirjak** [comment]
@shyim thanks for your answer. I updated my project to 6.5.5.2 but unfortunately, the error still occurs. 

Thanks for your help!

**Comment by michnhokn** [comment]
@shyim Same here. In our case this only happens for sales channels where the iso locale of the language does not match any snippet set because we use a different one the sales channel configuration.

**Comment by mschop** [comment]
Same here. PHP 8.2 / Shopware 6.5.7.2

**Comment by quisse** [comment]
With us, this was related to a bug in Shopware where it didn't pick up translations from files when they are located in a bundle (`src/BundleName`). Moving those to the `custom/static-plugins` directory (& clearing the translations cache) seemed to solve the issue.

**Comment by mschop** [comment]
The problem seems to be related to the function `\Frosh\TemplateMail\Services\MailFinderService::fixTranslator`. When I remove the function (and it's calling site), the bug completely disappears.

I don't know, what the purpose of this method should be, but it seems to be superfluous and buggy.

**Comment by michnhokn** [comment]
@mschop You are right. We also had issues with the translator fix. Basically the reason was the build in caching. We applied the following patches and now it works:
`MailFinderService.php`
```
--- a/vendor/store.shopware.com/froshplatformtemplatemail/src/Services/MailFinderService.php
+++ b/vendor/store.shopware.com/froshplatformtemplatemail/src/Services/MailFinderService.php
@@ -74,7 +74,9 @@
                     foreach ($searchFolder as $folder) {
                         $filePath = $path . '/email/' . $folder . '/' . $technicalName . '/' . $type . $supportedExtension;
                         if (file_exists($filePath) && $content = $availableLoader->load($filePath)) {
-                            $this->fixTranslator($businessEvent);
+                            if (!$returnFolder) {
+                                $this->fixTranslator($businessEvent);
+                            }

                             return $returnFolder ? $filePath : $content;
                         }
@@ -86,7 +88,7 @@
         return null;
     }

-    private function fixTranslator(TemplateMailContext $businessEvent): void
+    public function fixTranslator(TemplateMailContext $businessEvent): void
     {
         $criteria = new Criteria([$businessEvent->getContext()->getLanguageId()]);
         $criteria->addAssociation('locale');
```
`CachedMailFinderService.php`
```
--- a/vendor/store.shopware.com/froshplatformtemplatemail/src/Services/CachedMailFinderService.php
+++ b/vendor/store.shopware.com/froshplatformtemplatemail/src/Services/CachedMailFinderService.php
@@ -30,10 +30,20 @@
             . $returnFolder
         );

-        return $this->cache->get($cacheKey, function (CacheItem $cacheItem) use ($type, $technicalName, $businessEvent, $returnFolder) {
+        $fixTranslator = !$returnFolder;
+
+        $result = $this->cache->get($cacheKey, function (CacheItem $cacheItem) use ($type, $technicalName, $businessEvent, $returnFolder, &$fixTranslator) {
             $cacheItem->expiresAfter(3600);

+            $fixTranslator = false;
+
             return $this->mailFinderService->findTemplateByTechnicalName($type, $technicalName, $businessEvent, $returnFolder);
         });
+
+        if ($fixTranslator && \is_callable([$this->mailFinderService, 'fixTranslator'])) {
+            $this->mailFinderService->fixTranslator($businessEvent);
+        }
+
+        return $result;
     }
 }
```

**Comment by shyim** [comment]
Do you mind creating a PR?

**Comment by michnhokn** [comment]
@shyim Yeah I can do this 👍

**Comment by Tanzzwerg** [comment]
Thanks @michnhokn for providing a solution. Did you already create create a PR? We are looking forward to solving this issue in one of our projects 🤗

**Comment by shyim** [comment]
will be fixed with https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/commit/0a1379fea7455ca42450bcb70168c25b037c788b
