### ISSUE TITLE
Can't create new mail templates via the administration

### ISSUE THREAD

**Issue by jooleanth** [FriendsOfShopware/FroshPlatformTemplateMail#57]
### PHP Version

8.1

### Shopware Version

6.5.2.1

### Actual behaviour

When we try to open the create page for mail-templates, the vue template expects the froshTemplateMail extension which is not available at this point.

![Bildschirmfoto 2023-10-05 um 11 32 47](https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/assets/62592864/53b027e7-bf74-449c-aa6e-283adb077c19)

### Expected behaviour

I should be able create a new mail-template via the administration.

### Steps to Reproduce?

Install the Shopware Version 6.5.2.1 and the store.shopware.com/froshplatformtemplatemail version 2.0.2.
Then visit the route /admin#/sw/mail/template/create.
The exception can be inspected in the browser console.

**Comment by marvn-r3** [comment]
Can confirm the same issue with two of our Shops (SW 6.5.6.0 and SW 6.5.6.1 php 8.2)
