### ISSUE TITLE
Support language-code

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshPlatformTemplateMail#6]
Instead of `Language ID` there should be support for language code, f.e. de-DE

**Comment by zolthan** [comment]
Hi @shyim ,

is the inheritance written in the README correct?

custom/plugins/MyTheme/src/Resources/views/email/[en-GB]/order_transaction.state.paid/html.twig (Language Locale)
custom/plugins/MyTheme/src/Resources/views/email/[ID]/order_transaction.state.paid/html.twig (Saleschannel ID)
custom/plugins/MyTheme/src/Resources/views/email/[ID]/order_transaction.state.paid/html.twig (Language ID)
custom/plugins/MyTheme/src/Resources/views/email/global/order_transaction.state.paid/html.twig (Default)
Database saved values

I think it would make more sense to place the Language Locale between Language ID and Default, so it can be overwritten by IDs.

(sorry for commenting on closed issues again...)

Best Sebastian
