### ISSUE TITLE
Multiple Templates per Type

### ISSUE THREAD

**Issue by iMiMWeis** [FriendsOfShopware/FroshPlatformTemplateMail#62]
I have exported templates to files using the `frosh:template-mail:export` command. I have noticed, that some templates were not created, due to them being assigned to the same type.

It would be great if this plugin supported multiple templates per type.

Currently the identifier for email templates is the template type. However this would not work with multiple templates per type.

**Comment by amenk** [comment]
Not so much only a problem of the export command, might also be a problem on how to assign those different templates (we could add a `.1`,`.2` and so on suffix during the export) in the flow builder, right?

**Comment by fgiering** [comment]
Isn't this as easy as it sounds?

**Comment by amenk** [comment]
Not sure, about how to assign them in the flow builder. The export is probably not the problem. Is this what you mean @fgiering  ?

**Comment by fgiering** [comment]
![grafik](https://github.com/user-attachments/assets/99ce7ed5-25f3-4dd1-b24d-d325c7629ddf)
![grafik](https://github.com/user-attachments/assets/d97f73e7-15fb-46f5-8a81-1d1cd56b8c95)
We always put a description in the description field. The flow-builder is showing this to seperate between same template-types.
Does the plugin export and import the description field?
Isn't this an "replace-problem" on the import of the same teamplate-type?

**Comment by amenk** [comment]
As I understand it, the plugin does not import anything.

There is a export-to-theme function which creates the twig files based on the type of the mails in the database.
Then, when sending emails, the extensions seems to pick up the template from the filesystem, based on the type.

If you have multiple different templates with the same type and chose different ones in the flow builder, still both templates of that type would pull the same template.

This is also visible in the email template list:

![image](https://github.com/user-attachments/assets/d3e56cd1-1b88-47b2-a4bc-7452245a24c1)

It needs some concept how to implement that. Maybe in the database, a twig template could be linked and we still could create email template entries in the admin panel.

**Comment by fgiering** [comment]
Yes. I see. There would be some mapping necessary.

**Comment by amenk** [comment]
@shyim what do you think about this?

**Comment by amenk** [comment]
Idea would be to store the templates like this ...

![Image](https://github.com/user-attachments/assets/5a12922f-cda2-4613-a430-6abd1cdf11c2)

**Comment by amenk** [comment]
Implemented in #75 
Was still seems to be missing the the indication in the admin panel, that a template is overwritten.
