### ISSUE TITLE
mjml server requests

### ISSUE THREAD

**Issue by thbader** [FriendsOfShopware/FroshPlatformTemplateMail#63]
### Question

Hi,
I've checked usage of mjml templates, but I can't see if the compiled templates (with html) are cached.
Is there a request for every usage of an mjml email or only one after clearing the cache.

Best regards
Thomas

**Comment by shyim** [comment]
they are cached with https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/blob/main/src/Services/CachedMailFinderService.php in production
