### ISSUE TITLE
Match themes of salesChannel from Symfony bundles

### ISSUE THREAD

**Issue by Vhulcan** [FriendsOfShopware/FroshPlatformTemplateMail#65]
### Please describe the feature you would like to see implemented.

Currently the `MailFinderService` only looks for Shopware apps or plugins and so it cannot match themes of salesChannels from Symfony Bundles.

At our company we use Symfony Bundles to add themes, and if you have multiple themes it will currently just take the first theme in alphabetical order.

**Comment by shyim** [comment]
Can you make a PR? :)

**Comment by Vhulcan** [comment]
@shyim PR created! 😃
