### ISSUE TITLE
Parameter value "salesChannelId" cannot be converted to "string".

### ISSUE THREAD

**Issue by develth** [FriendsOfShopware/FroshPlatformTemplateMail#70]
### PHP Version

8.2

### Shopware Version

6.6.3

### Plugin Version

3.0.4

### Actual behaviour

Before Admin Login, request new Passwort (`/admin#/login/recovery`).
There is an Error Thrown in FlowSubscriber::86 (`$salesChannelId = $dataBag->getString('salesChannelId');`):

### Internal Server Error
> Parameter value "salesChannelId" cannot be converted to "string".

### Expected behaviour

Mail should be sent without Error

### Steps to Reproduce?

Request new Admin-Passwort (`/admin#/login/recovery`).

**Comment by AndySpitzbub** [comment]
Same for us. No mails generated within Shopware admin parts could be sent.
