### ISSUE TITLE
How to run PHPunit / linters

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/FroshPlatformTemplateMail#76]
### Question

For easier contribution, we should document how to run PHPunit and so on locally or link to such resources.

I managed to run PHPunit locally inside a Shopware shop

I managed to run PHPCSFixer:

```bash
$ composer require --dev friendsofphp/php-cs-fixer
$ vendor/bin/php-cs-fixer fix --rules=@PER-CS2.0,no_unused_imports .
```

How to run PHPstan?

```bash
$ cd vendor/frosh/frosh-platform-template-mail
$ composer require --dev phpstan/phpstan-symfony

vendor/bin/phpstan analyze
Note: Using configuration file /home/me/projects/shopware-shopware/vendor/frosh/frosh-platform-template-mail/phpstan.neon.dist.
Invalid configuration:
Unexpected item 'parameters › symfony'.
Invalid configuration:
Unexpected item 'parameters › type_coverage'.
```

**Comment by shyim** [comment]
You need a shopware/shopware setup, composer require the plugin and afterwards run vendor/bin/phpstan to the plugin

**Comment by amenk** [comment]
Wondering if we should add that to the README.md 😃
Of course the dev setup might differ a bit - I usually work in vendor (via composer install --prefer-source), others might put such plugins into custom/ when working on it.

For the record:

```bash
shopware-shopware$ vendor/bin/phpstan analyse -- ./vendor/frosh/frosh-platform-template-mail
Note: Using configuration file <...>shopware-shopware/phpstan.neon.dist.
   320/12693 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   2%
```

looks like it would analyse the full shopware, but actually it only scans this file and then analyses only the plugin - because all files are needed to get proper analysis. This confused me at first.
