### ISSUE TITLE
Directories containing a dot won't work 

### ISSUE THREAD

**Issue by pt1602** [FriendsOfShopware/FroshPlatformTemplateMail#8]
Hello guys from FriendsOfShopware,
I recently started working with your plugin again and noticed that every directory or maybe mail type with a dot in it wont work.

Here are the ones I have tested so far: 
order_delivery.state.shipped
order_transaction.state.paid_partially

Thanks for your help :smile:

**Comment by shyim** [comment]
Maybe this is your fix?
https://github.com/FriendsOfShopware/FroshPlatformTemplateMail/commit/d84c1d5f0b4fef55d999a15d50c74290b20affe9

**Comment by pt1602** [comment]
Thanks for your response. I will try that and give feedback.

**Comment by pt1602** [comment]
Tested it today and now it works fine again. Thanks!
